### ISSUE TITLE
MessageRouting fails for come channels in User Handoff scenario

### ISSUE THREAD

**Issue by edwardbakker** [tompaana/bot-message-routing#1]
Message routing fails when using the combination of Messenger and Skype. 
Example: 
Messenger : Customer Service Agent
Skype: Customer

- In Messenger use "command add aggregation" to aggregate all request.
- In Skype request for User Handoff.
- Conversation between Service Agent and Customer is established
- Customer sends message which is received by the Service Agent
- Service Agent sends message which is NOT received by the Customer

When testing the above scenario with Messanger to Bot Emulator or Skype to Bot Emulator it all works fine...

Let me know if you need more info :)

**Comment by tompaana** [comment]
Again (since this conversation started in Twitter) thank you! I will certainly look into this.

Unfortunately, I haven't had time (and been quite lazy to be honest) to write down my plan, but in a nutshell: This project is for the core functionality for the human hand-off in C#. There will be no command handling or any other stuff outside the core here. However, the original project (https://github.com/tompaana/intermediator-bot-sample/) will be modified to use this project and will still feature command handling etc.

As soon as the basic functionality is verified to work, this core project will be published as a Nuget package.

**Comment by edwardbakker** [comment]
OK, Sounds good! In the meantime I will do some more testing :).
Let me know if you need help!
